apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
#  annotations:
#    metallb.universe.tf/loadBalancerIPs: default
spec:
  externalIPs:
    - 176.53.163.61
#    - 91.186.199.148
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
#  type: LoadBalancer
  type: ClusterIP