apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:

#  На какие pods делать запросы
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 80

#      На каком порту запускается приложение
      targetPort: 8080
