---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
#    kubectl get nodes -o wide
#    kubectl -n ingress-nginx get svc
    - 10.200.70.220-10.200.70.223
#    - 176.53.163.61

  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default